name: voting-backend
type: Microsoft.App/ContainerApps
properties:
  managedEnvironmentId: /subscriptions/8c86bf0d-09aa-48d7-84a6-6c181ae13f10/resourceGroups/voting-containerapps/providers/Microsoft.App/managedEnvironments/voting-containerapps-env
  template:
    containers:
    - name: redis
      image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
      env:
      - name: TCP_PORT
        value: 6379
      - name: ALLOW_EMPTY_PASSWORD
        value: 'yes'
      resources:
        cpu: 0.5
        memory: 1Gi
      volumeMounts:
      - mountPath: /data/redis
        volumeName: data    
    volumes:
    - name: data
      storageType: EmptyDir
    scale:
      maxReplicas: 1
      minReplicas: 1